import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "~~/components/ui/toaster";
import { cn } from "~~/lib/utils";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "p-2")}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
